### ISSUE TITLE
Runtime Error when i Try to run the demo

### ISSUE THREAD

**Issue by b1ackout** [bubasuma/yii2-simplechat#16]
An exception has been thrown during the rendering of a template ("The file or directory to be published does not exist: C:\xampp\htdocs\yii2-app-advanced/vendor\bower/twig.js") in "index.twig" at line 4.
↵
Caused by: Invalid Parameter – yii\base\InvalidParamException

The file or directory to be published does not exist: C:\xampp\htdocs\yii2-app-advanced/vendor\bower/twig.js

in C:\xampp\htdocs\yii2-app-advanced\vendor\yiisoft\yii2\web\AssetManager.php at line 452

**Comment by bubasuma** [comment]
Hi @b1ackout 
Please make sure u've  installed `twig` dependencies.
read this [wiki](https://github.com/bubasuma/yii2-simplechat/wiki/Using-twig-as-template-engine) for reference
