### ISSUE TITLE
submit problem

### ISSUE THREAD

**Issue by dinastia** [bubasuma/yii2-simplechat#4]
After submit a chat, the same message repeat continuously . 
although just one record was save. Just the version 1.00 is avaliable to install.

**Comment by bubasuma** [comment]
Are you running the extension in demo mode?
Please provide screen shots for more details!

**Comment by dinastia** [comment]
Thank you for your quickly reply. I did run the command "yii simplechat"  and it showed "Yii2 SimpleChat Demo" mode. In the usage instructions you  put in the MessageController this line: "use bubasuma\simplechat\controllers\ControllerTrait", but in the v1.0.0 version don't have this file.

Congratulation to great work, and sorry if this configuration is so obvious and make you lost your time.

Thanks again.

**Comment by bubasuma** [comment]
Hi, 
I am developing the new version of the extension (2.0.0-alpha), that is incompatible with previous versions. The master branch contains this version. Please look at https://github.com/bubasuma/yii2-simplechat/tree/v1.0.0 for 1.0.0

**Comment by dinastia** [comment]
this it the screen shot of the problem.
![screen shot 2016-01-27 at 4 55 23 pm](https://cloud.githubusercontent.com/assets/5226232/12624607/0cab1092-c517-11e5-8348-40b359cfc157.png)

**Comment by bubasuma** [comment]
Hi,
Please go here https://github.com/bubasuma/yii2-simplechat/tree/v1.0.0, and follow instructions.
I cannot reproduce this bug.
Judging by your screen shot your are not using the extension in demo mode.
Send me your configuration and every extra code you have wrote to run the extension.
