### ISSUE TITLE
without twig

### ISSUE THREAD

**Issue by veyselsahin** [bubasuma/yii2-simplechat#5]
Hi Buba Suma is there any way to use this module without twig engine ? 
You was wrote widgets but i cannot use these widgets is there any demo i didnt integrate can you help bro. Thanks

**Comment by bubasuma** [comment]
Hi,
Yes, you can integrate this extension with any web template engine: Twig, Smarty, ... or PHP itself. You can even combine together. The only thing you have to do is to specify it in views names. php is the default render in yii2.
Using ConversationWidget in your `conversations.php`
```php
    \bubasuma\simplechat\ConversationWidget::widget([
       'dataProvider' => $conversationDataProvider,
       'itemView' => __DIR__ . '/conv',      
        'user' => [
            'id' => $user->id,
            //...
        ],
        'clientOptions' => [
            //...
            'currentCssClass' => 'current',
            'unreadCssClass' => 'unread',
            'baseUrl' => $asset->baseUrl
            //...
        ]
    ]);
```
Please reply to this comment, if you are satisfied.

**Comment by newerton** [comment]
Hi @bubasuma !

You could write a wiki without using the Twig?

**Comment by bubasuma** [comment]
Hi @newerton 
ok.

**Comment by jsobers1331** [comment]
I agree, this would help alot.

**Comment by newerton** [comment]
+1
