### ISSUE TITLE
HumHub integration

### ISSUE THREAD

**Issue by WebCrew** [bubasuma/yii2-simplechat#6]
Hi bubasuma,

first I want to say thank You cause of Your awesome work You have done. I love Your chat solution and I would be super happy if You try to make a **HumHub Module** for us cause HumHub has by default only a chat which is not more as a shoutbox, so no user to user private chat feature. Cause Your chat is based on **Yii2** it should be _not to hard_ to make a HumHub module cause HH is also using Yii2.

[HumHub Module Documentation](https://www.humhub.org/docs/guide-dev-module-index.html)

Here You can see our shoutbox like chat which we have done for HumHub. As You can see it lags on user to user private chat. Your chat is not so simple as You think :+1: 

[HumHub Basic Chat](https://github.com/petersmithca/humhub-basic-chat)

I hope You`ll hear my begggging lol and You find the time to make it possible.
Kind regards, Andy

**Comment by bubasuma** [comment]
Thank You @WebCrew.
Let me think about. 
My priority for now is the next release (stable version) of the extension.

**Comment by WebCrew** [comment]
Ok I understand Your prorities, I wish You good luck and all the best for the future.
