### ISSUE TITLE
What would you like to see in the next version

### ISSUE THREAD

**Issue by bubasuma** [bubasuma/yii2-simplechat#7]
Dear users,
What would you like to see in the next stable version **v2.0.0** of `yii2-simplechat`?
Fell free to comment!

**Comment by dronz** [comment]
Здравствуйте, опишу свое видение:
-убрать загрузку всех моделей в bubasuma/yii2-simplechat/controllers/DefaultController.php 95 $users = $this->getUsers([$user->id, $contact['id']]); это сильно грузит сервер и не вижу зачем оно
-также, есть опасения на счет нагрузки на сервер при опросе сервера. может есть смысл использовать dklab realplexor или xmpp. Если оставить виджет на странице /message(s) то думаю норм. но если его вставить на каждой странице  - могут возникнуть проблемы. Хотелось бы чтобы на каждой странице можно было выести кнопочку с количеством непрочитанных сообщений, при нажатии на которую вылезет modal со списком посетителей или даже с чатом.

В текущей версии не подхватывает пути assets для шаблонов из папки tmpl, может что не так делаю.

С Уважением и спс за Ваш труд.

**Comment by bubasuma** [comment]
Hi @dronz 
this [line](https://github.com/bubasuma/yii2-simplechat/blob/master/controllers/DefaultController.php#L95) is not necessary when integrating this extension. It's only for demo application. You don't need these functions at all: [getUsers() ](https://github.com/bubasuma/yii2-simplechat/blob/master/controllers/DefaultController.php#L141), [setUser() ](https://github.com/bubasuma/yii2-simplechat/blob/master/controllers/DefaultController.php#L136), [getUser() ](https://github.com/bubasuma/yii2-simplechat/blob/master/controllers/DefaultController.php#L128) unless you want to override the [parent](https://github.com/bubasuma/yii2-simplechat/blob/master/controllers/ControllerTrait.php#L131) function and [actionLoginAs()](https://github.com/bubasuma/yii2-simplechat/blob/master/controllers/DefaultController.php#L103).
the [issue](https://github.com/yiisoft/yii2-twig/issues/40) with assets had been reported in [yii2-twig](https://github.com/yiisoft/yii2-twig). I suppose you are using the last stable version of `yii2-twig` because this issue if fixed but not released yet. I suggest you to fork and release yourself. Another alternative is to create extension for twig that include your own functions. Then add it to your twig config like follow
```php
[
    'components' => [
        'view' => [
            'class' => 'yii\web\View',
            'renderers' => [
                'twig' => [
                    'class' => 'yii\twig\ViewRenderer',
                    'extensions' => [new MyExtension()],
                ],
                // ...
            ],
        ],
    ],
]
```
Thanks for your comment.
