### ISSUE TITLE
Not able to get your extension to work?

### ISSUE THREAD

**Issue by jsobers1331** [bubasuma/yii2-simplechat#8]
> use bubasuma\simplechat\controllers\ControllerTrait;

Is this still valid?

Also, not getting demo to display either. I followed everything in your instructions so i'm uncertain what I'm doing wrong.

also when I did the migration I noticed the following error:

```
C:\xampp\htdocs\yii>yii simplechat/start
Yii2 SimpleChat Demo

Yii Migration Tool (based on Yii v2.0.8)

No new migrations found. Your system is up-to-date.
Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view n
ot found: 1146 Table 'yii.simplechat_audit_entry' doesn't exist
The SQL being executed was: UPDATE `simplechat_audit_entry` SET `duration`=0.158
19597244263, `memory_max`=5456376 WHERE `id`=42850'

in C:\xampp\htdocs\yii\vendor\yiisoft\yii2\db\Schema.php:633

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'yii.simplechat_audit_entry' doesn't exist
)
```

I'm using Yii2 Advance Framework.

**Comment by bubasuma** [comment]
Hi @jsobers1331 
Yes. `use bubasuma\simplechat\controllers\ControllerTrait` is still valid. 
You are getting the error below:
```console
Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view n
ot found: 1146 Table 'yii.simplechat_audit_entry' doesn't exist
The SQL being executed was: UPDATE `simplechat_audit_entry` SET `duration`=0.158
19597244263, `memory_max`=5456376 WHERE `id`=42850'

in C:\xampp\htdocs\yii\vendor\yiisoft\yii2\db\Schema.php:633

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'yii.simplechat_audit_entry' doesn't exist
)
```
because the fixture properties are overridden in your config file. Comment it, if you wanna run the demo. Pay attention to this code from [Fixture](https://github.com/bubasuma/yii2-simplechat/blob/master/console/FixtureController.php#L27-L45) controller
```php
    /**
     * @var array Additional data providers that can be created by user and will be added to the    Faker generator.
     * More info in [Faker](https://github.com/fzaninotto/Faker.) library docs.
     */
    public $providers = [
        'bubasuma\simplechat\tests\unit\fixtures\providers\Avatar',
    ];
    /**
     * @var string default namespace to search fixtures in
     */
    public $namespace = 'bubasuma\simplechat\tests\unit\fixtures';
    /**
     * @var string Alias to the template path, where all tables templates are stored.
     */
    public $templatePath = '@bubasuma/simplechat/tests/unit/fixtures/templates';
    /**
     * @var string Alias to the fixture data path, where data files should be written.
     */
    public $fixtureDataPath = null;
```
and this other from [Command] (https://github.com/bubasuma/yii2-simplechat/blob/master/console/DefaultController.php#L71-L75) controller
```php
$this->module->controllerMap['fixture'] = [
    'class' => FixtureController::className(),
    'interactive' => $this->interactive,
    'language' => $this->language,
];
```
I hope, this will help you.

**Comment by jsobers1331** [comment]
Hi Thanks for the feedback for some reason i didn't see your reply until now @bubasuma .

Now when I'm trying to render the the chat at /messages, I get the following error:

```
Twig_Error_Runtime

An exception has been thrown during the rendering of a template ("The file or directory to be published does not exist: ..../vendor\bower/twig.js") in "index.twig" at line 4.
```

trying to figure out why it's missing this file.

I even followed https://github.com/yiisoft/yii2-twig/blob/master/docs/guide/installation.md installation instructions in case i missed anything but no joy.

**Comment by bubasuma** [comment]
Hi @jsobers1331 
Pay attention to the [composer.json](https://github.com/bubasuma/yii2-simplechat/blob/master/composer.json) file. Since `yii2-simplechat` lets you choose the template engine you prefer, it does not include `twig` as required dependency. So if you really want to use `twig` as the template engine, you should include manually twig packages in your project's `composer.json`.

**Comment by jsobers1331** [comment]
I just trying to get it running, I will learn eventually but i just want to see it running so i can integrate it into my project.

At the moment, ideally i would like to change the template engine to PHP for your views. But not sure how to do that yet. So focusing on getting it to run. Thanks for the quick reply.

**Comment by jsobers1331** [comment]
adding your last statement worked. However now it telling me 

"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yiiopensecret.simplechat_audit_entry' doesn't exist"

I'll try creating it manually, not sure why the migration scripts didn't take care of it.

**Comment by bubasuma** [comment]
Are you running the demo or you are running from your app?

**Comment by jsobers1331** [comment]
I'm running the demo. I have a audit_entry table in my db, which is used from https://github.com/bedezign/yii2-audit

**Comment by bubasuma** [comment]
When you are running the module `simplechat`, all tables names are prefixed by the module name. So if you are using 3rd parties that work with DB and listed in your application `bootstrap`, please comment them when running the demo.
The reason why the `simplechat` demo adds prefix to its tables name is to avoid conflict with your application tables. Pay attention to [this](https://github.com/bubasuma/yii2-simplechat/blob/master/Module.php#L105-L111).

**Comment by jsobers1331** [comment]
ohhhhhhh, i got it to work. I had to disable the built-in yii2 session DB handling too to get it to work. Now i just need to find a way to integrate your module without causing similar issues going forward.
 
thank you for your patience and quick replies.

**Comment by bubasuma** [comment]
I am happy to help.
Don't worry. You won't need to declare `simplechat` in `modules` neither in `bootstrap` when you use it in your app. This is required only when you are running the demo. see [usage](https://github.com/bubasuma/yii2-simplechat#usage)

**Comment by jsobers1331** [comment]
Ohhhhhhhhhhhhhhh, i didn't get that from the instructions in the README file. I thought it was needed in the bootstrap all the time.  :)

**Comment by jsobers1331** [comment]
Sorry one more question. I was wondering if the correct way to do integration. Cause i see in your usage documentation we have models but the DB doesn't have any tables. 

Where is the table schema i should use?

**Comment by jsobers1331** [comment]
should i run the test tables and fixtures command and then run the clean command?

**Comment by jsobers1331** [comment]
Thanks for the instruction. I followed it and was able to create the message table in the DB.

However, since then i haven't been able to get it to work outside of the Demo. Right now, when i try to go to route "messages", all I get is 404 error.

`	exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "messages".'`

**Comment by bubasuma** [comment]
@jsobers1331
You have to add routing rules in  your `urlManager` component in order to reach your Controller. The demo routing is not working because you removed demo module from bootstrapping modules (that's correct if you are integrating the chat into your app). Now You just have to include similar routing in your app routing component.

**Comment by jsobers1331** [comment]
ok i implemented the following:

```
'urlManager' => [
                'enablePrettyUrl' => true,
                'rules' => [
                    // your rules go here
                    'messages' => 'messages/index', 
                ],
            // ...
        ],
```

I copied the twig files from default folder in your module but still no joy.

**Comment by epulgaron** [comment]
awsome exension, one question, how can i use my user table instead of yours? sorry 4 my bad english

**Comment by bubasuma** [comment]
@epulgaron 
You can override everything in the extension. Migrations that come out of box are just for Demo. You don't even need simplechat module when integrating this extension to your app. You need only to extend base models and use controllerTrait in your message controller. The example is illustrated in demo.

**Comment by KushShar** [comment]
hi bubasuma It is nice but I have an one issue in that. I have an one JS error 
ReferenceError: twig is not defined
So what I have to do about that please rply.
